### ISSUE TITLE
Add optional input for Azure endpoint to allow clouds other than Azure Public

### ISSUE THREAD

**Issue by davesee** [sxwei123/azure-log-analytics-data-collector-client#29]
The implementation of this client in Azure Gov currently produces the following error: "uncaughtException: Cannot access 'LogAnalyticsTransport' before initialization".

Adding the optional input would allow for any cloud to work by specifying its own endpoint URL.

Azure Gov endpoint example:
https://learn.microsoft.com/en-us/azure/azure-government/compare-azure-government-global-azure
ods.opinsights.azure.com vs ods.opinsights.azure.us

Url to be updated with the endpoint to be optionally overwritten.
https://github.com/sxwei123/azure-log-analytics-data-collector-client/blob/master/src/index.ts#L58

**Comment by davesee** [comment]
Created and tested the changes in [my fork](https://github.com/davesee/azure-log-analytics-data-collector-client) and published for testing [in npm](https://www.npmjs.com/package/azure-log-analytics-data-collector).

Please let me know if you are available to process a PR @sxwei123

**Comment by sxwei123** [comment]
Thanks @davesee, PR has been merged.
