### ISSUE TITLE
Thank you for the docs

### ISSUE THREAD

**Issue by justinmchase** [sxwei123/azure-log-analytics-data-collector-client#38]
> To get your WORKSPACE_ID and PRIMARY_KEY_OR_SECONDARY_KEY, in your workspace go to Agents management -> Log Analytics agent instructions.

I just wanted to thank you for putting this in your docs ☝️ for the life of me I couldn't figure it out! They really hide that information.

**Comment by sxwei123** [comment]
@justinmchase Haha, it took me a lot of time to figure it out. Glad to know it helped you!
